"""
Example 4: Analyzing and Fixing Failures

Demonstrates:
- How to analyze evaluation failures systematically
- Common failure patterns and root causes
- Fixing agent instructions
- Fixing tool implementations
- Iterative improvement workflow

Key Pattern:
1. Read results file
2. Identify failure pattern
3. Apply targeted fix
4. Re-run evaluation
5. Verify improvement

Run:
python examples/example_4_analysis_and_fixes.py
"""

import asyncio
import sys
import os

# Add parent directory to path for imports
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from utils import load_api_key


async def demo_analysis_and_fixes():
    """
    Demonstrate analyzing and fixing evaluation failures.

    Shows:
    1. Reading and analyzing results files
    2. Common failure patterns
    3. Systematic debugging approach
    4. Fixing agent instructions
    5. Fixing tool implementations
    6. Iterative improvement workflow
    """
    print("\n" + "=" * 80)
    print("Example 4: Analyzing and Fixing Failures")
    print("=" * 80)

    # Demo 1: Reading results
    print("\n" + "-" * 80)
    print("DEMO 1: Reading Evaluation Results")
    print("-" * 80)
    print()
    print("Results File: integration.evalset.json.results")
    print()
    print("Manual Analysis:")
    print("  $ cat integration.evalset.json.results | grep 'pass'")
    print("  $ python -m json.tool integration.evalset.json.results")
    print()
    print("Programmatic Analysis:")
    print("  from utils import analyze_results")
    print("  analysis = analyze_results('integration.evalset.json.results')")
    print("  print_evaluation_summary(analysis)")
    print()
    print("Key Information to Extract:")
    print("  • Which tests passed/failed")
    print("  • Actual vs expected responses")
    print("  • Actual vs expected tool calls")
    print("  • Score values (response_match, tool_trajectory)")
    print()

    # Demo 2: Common failure patterns
    print("-" * 80)
    print("DEMO 2: Common Failure Patterns")
    print("-" * 80)
    print()
    print("Pattern 1: Low Response Match Score")
    print("  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
    print()
    print("  Symptom:")
    print("    response_match_score: 0.45")
    print("    tool_trajectory_avg_score: 1.0")
    print("    Status: ❌ FAILED")
    print()
    print("  Root Causes:")
    print("    1. Agent using different phrasing")
    print("    2. Missing information in response")
    print("    3. Extra unnecessary information")
    print("    4. Wrong tone or format")
    print()
    print("  Example:")
    print("    Expected: 'The living room lights are now on.'")
    print("    Actual:   'I turned on some lights for you!'")
    print("    Issue:    Missing location specificity")
    print()
    print("Pattern 2: Low Tool Trajectory Score")
    print("  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
    print()
    print("  Symptom:")
    print("    response_match_score: 0.95")
    print("    tool_trajectory_avg_score: 0.33")
    print("    Status: ❌ FAILED")
    print()
    print("  Root Causes:")
    print("    1. Wrong tool parameters")
    print("    2. Tool not called")
    print("    3. Wrong tool selected")
    print("    4. Parameter extraction errors")
    print()
    print("  Example:")
    print("    Expected: set_device_status(location='living_room', ...)")
    print("    Actual:   set_device_status(location='livingroom', ...)")
    print("    Issue:    Underscore vs no space")
    print()
    print("Pattern 3: Both Scores Low")
    print("  ━━━━━━━━━━━━━━━━━━━━━━━━━━")
    print()
    print("  Symptom:")
    print("    response_match_score: 0.25")
    print("    tool_trajectory_avg_score: 0.0")
    print("    Status: ❌ FAILED")
    print()
    print("  Root Causes:")
    print("    1. Agent didn't understand query")
    print("    2. Agent refused to help")
    print("    3. Missing tools")
    print("    4. Poor instruction quality")
    print()
    print("  Example:")
    print("    Query:    'Turn on the living room lights'")
    print("    Actual:   'I cannot help with that request.'")
    print("    Issue:    Agent not recognizing capability")
    print()

    # Demo 3: Systematic debugging
    print("-" * 80)
    print("DEMO 3: Systematic Debugging Approach")
    print("-" * 80)
    print()
    print("The Debug Workflow:")
    print()
    print("Step 1: Identify the Pattern")
    print("  ┌─────────────────────────────────────┐")
    print("  │ Look at failed tests:               │")
    print("  │ • All same error? → Systematic bug  │")
    print("  │ • Random errors? → Specific cases   │")
    print("  │ • One type of test? → Category bug  │")
    print("  └─────────────────────────────────────┘")
    print()
    print("Step 2: Determine Root Cause")
    print("  ┌─────────────────────────────────────┐")
    print("  │ Check scores:                       │")
    print("  │ • Low response only? → Instructions │")
    print("  │ • Low tool only? → Parameters       │")
    print("  │ • Both low? → Understanding         │")
    print("  └─────────────────────────────────────┘")
    print()
    print("Step 3: Apply Targeted Fix")
    print("  ┌─────────────────────────────────────┐")
    print("  │ Based on root cause:                │")
    print("  │ • Instructions → Update prompts     │")
    print("  │ • Parameters → Fix tool calls       │")
    print("  │ • Understanding → Add examples      │")
    print("  └─────────────────────────────────────┘")
    print()
    print("Step 4: Verify Fix")
    print("  ┌─────────────────────────────────────┐")
    print("  │ Re-run evaluation:                  │")
    print("  │ • Same tests pass? → Fixed!         │")
    print("  │ • New failures? → Regression        │")
    print("  │ • Still failing? → Wrong fix        │")
    print("  └─────────────────────────────────────┘")
    print()

    # Demo 4: Fixing instructions
    print("-" * 80)
    print("DEMO 4: Fixing Agent Instructions")
    print("-" * 80)
    print()
    print("Problem: Vague or inconsistent responses")
    print()
    print("❌ BEFORE (Broken):")
    print("  instruction = '''")
    print("  You control smart home devices.")
    print("  Help the user with their requests.")
    print("  '''")
    print()
    print("  Result: 'I turned on some lights!'")
    print("  Issue: Missing specificity, wrong tone")
    print()
    print("✅ AFTER (Fixed):")
    print("  instruction = '''")
    print("  You are a home automation assistant.")
    print()
    print("  When controlling devices:")
    print("  1. Always confirm the specific device and location")
    print("  2. Use this exact format: 'The {location} {device} are now {status}.'")
    print()
    print("  Example:")
    print("  User: 'Turn on the living room lights'")
    print("  You: 'The living room lights are now on.'")
    print("  '''")
    print()
    print("  Result: 'The living room lights are now on.'")
    print("  Improvement: Specific, consistent format")
    print()
    print("Key Improvements:")
    print("  ✅ Added response format template")
    print("  ✅ Included concrete example")
    print("  ✅ Specified required information (location, device, status)")
    print()

    # Demo 5: Fixing tool parameters
    print("-" * 80)
    print("DEMO 5: Fixing Tool Parameter Issues")
    print("-" * 80)
    print()
    print("Problem: Wrong parameters passed to tools")
    print()
    print("❌ BEFORE (Broken):")
    print("  Expected: set_device_status(location='living_room', ...)")
    print("  Actual:   set_device_status(location='livingroom', ...)")
    print("  Score:    0.67 (parameter mismatch)")
    print()
    print("Root Cause: Agent not extracting location correctly")
    print()
    print("✅ FIX 1: Update Tool Description")
    print("  def set_device_status(")
    print("      location: str,  # Use underscores: 'living_room', 'bed_room'")
    print("      device_id: str,")
    print("      status: str,")
    print("  ):")
    print("      '''")
    print("      Control smart home devices.")
    print()
    print("      Args:")
    print("          location: Room name with underscore (living_room, bed_room)")
    print("          device_id: Device type (lights, thermostat)")
    print("          status: Device state (on, off, or temperature)")
    print()
    print("      Examples:")
    print("          set_device_status('living_room', 'lights', 'on')")
    print("          set_device_status('bed_room', 'thermostat', '72')")
    print("      '''")
    print()
    print("✅ FIX 2: Add to Agent Instructions")
    print("  instruction = '''")
    print("  Important: Use underscores in location names:")
    print("  - 'living room' → 'living_room'")
    print("  - 'bedroom' → 'bed_room'")
    print("  - 'kitchen' → 'kitchen'")
    print("  '''")
    print()
    print("Result: Tool parameters now match expectations!")
    print()

    # Demo 6: Adding examples
    print("-" * 80)
    print("DEMO 6: Adding Examples to Instructions")
    print("-" * 80)
    print()
    print("Problem: Agent doesn't understand complex queries")
    print()
    print("❌ BEFORE:")
    print("  Query:  'Turn off all devices in the kitchen'")
    print("  Result: 'I cannot help with that request.'")
    print("  Issue:  Agent doesn't recognize 'all devices' pattern")
    print()
    print("✅ AFTER:")
    print("  instruction = '''")
    print("  You control smart home devices.")
    print()
    print("  Example Queries and Actions:")
    print()
    print("  Query: 'Turn on the living room lights'")
    print("  Action: set_device_status('living_room', 'lights', 'on')")
    print()
    print("  Query: 'Turn off all devices in the kitchen'")
    print("  Action: set_device_status('kitchen', 'lights', 'off')")
    print("          (Handle each device type)")
    print()
    print("  Query: 'Set bedroom temp to 72'")
    print("  Action: set_device_status('bed_room', 'thermostat', '72')")
    print("  '''")
    print()
    print("Result: Agent now handles complex queries!")
    print()

    # Demo 7: Iterative improvement
    print("-" * 80)
    print("DEMO 7: Iterative Improvement Workflow")
    print("-" * 80)
    print()
    print("Iteration 1:")
    print("  ┌────────────────────────────────┐")
    print("  │ Run:    adk eval agent tests   │")
    print("  │ Result: 2/5 passed (40%)       │")
    print("  │ Issue:  Vague responses        │")
    print("  │ Fix:    Add response template  │")
    print("  └────────────────────────────────┘")
    print()
    print("Iteration 2:")
    print("  ┌────────────────────────────────┐")
    print("  │ Run:    adk eval agent tests   │")
    print("  │ Result: 4/5 passed (80%)       │")
    print("  │ Issue:  Wrong location format  │")
    print("  │ Fix:    Update tool description│")
    print("  └────────────────────────────────┘")
    print()
    print("Iteration 3:")
    print("  ┌────────────────────────────────┐")
    print("  │ Run:    adk eval agent tests   │")
    print("  │ Result: 5/5 passed (100%) ✅   │")
    print("  │ Status: Ready to deploy!       │")
    print("  └────────────────────────────────┘")
    print()
    print("Key Lessons:")
    print("  • Each iteration fixes ONE category of issues")
    print("  • Verify improvement after each fix")
    print("  • Don't fix everything at once")
    print("  • Track what changed between runs")
    print()

    # Demo 8: Regression prevention
    print("-" * 80)
    print("DEMO 8: Preventing Regressions")
    print("-" * 80)
    print()
    print("What is a Regression?")
    print("  • Previously passing tests now fail")
    print("  • Caused by changes to fix other issues")
    print("  • Can be subtle and hard to spot")
    print()
    print("How to Prevent:")
    print()
    print("1. Run Full Test Suite After Every Change")
    print("   $ adk eval agent all_tests.evalset.json")
    print("   (Not just the tests you're fixing)")
    print()
    print("2. Add Regression Tests")
    print("   • When you fix a bug, add a test for it")
    print("   • Ensures bug doesn't come back")
    print()
    print("3. Use Version Control")
    print("   # Before making changes")
    print("   $ git checkout -b fix-location-bug")
    print("   # Make changes")
    print("   $ adk eval agent tests")
    print("   # If regression occurs, easy to rollback")
    print()
    print("4. Automate in CI/CD")
    print("   # In .github/workflows/test.yml:")
    print("   - name: Run agent evaluation")
    print("     run: |")
    print("       adk eval agent tests.evalset.json")
    print()

    # Demo 9: Advanced techniques
    print("-" * 80)
    print("DEMO 9: Advanced Debugging Techniques")
    print("-" * 80)
    print()
    print("Technique 1: Isolate Failures")
    print("  • Create minimal evalset with just failing test")
    print("  • Easier to debug without noise")
    print("  • Faster iteration cycle")
    print()
    print("Technique 2: Compare Expected vs Actual")
    print("  $ diff <(echo '$expected') <(echo '$actual')")
    print("  • Spot exact differences")
    print("  • Identify patterns in failures")
    print()
    print("Technique 3: Enable Observability")
    print("  from google.adk.plugins.logging_plugin import LoggingPlugin")
    print("  runner = InMemoryRunner(")
    print("      agent=agent,")
    print("      plugins=[LoggingPlugin()]  # See agent's thinking!")
    print("  )")
    print()
    print("Technique 4: A/B Test Instructions")
    print("  • Create two agent versions")
    print("  • Run same evalset on both")
    print("  • Compare pass rates")
    print("  • Choose better performing version")
    print()

    # Summary
    print("=" * 80)
    print("✅ Analysis and Fixes Complete!")
    print("=" * 80)
    print()
    print("Key Takeaways:")
    print()
    print("  ✅ Systematic approach: Identify → Diagnose → Fix → Verify")
    print("  ✅ Low response score → Fix instructions")
    print("  ✅ Low tool score → Fix parameters/descriptions")
    print("  ✅ Both low → Add examples and improve understanding")
    print("  ✅ Iterate until 100% pass rate")
    print("  ✅ Prevent regressions with full test suite")
    print()
    print("Quick Reference:")
    print()
    print("┌──────────────────────┬────────────────────────────────┐")
    print("│ Symptom              │ Fix                            │")
    print("├──────────────────────┼────────────────────────────────┤")
    print("│ Low response score   │ Update instruction format      │")
    print("│ Low tool score       │ Fix tool descriptions/params   │")
    print("│ Both low             │ Add examples, improve clarity  │")
    print("│ Random failures      │ Check for ambiguous inputs     │")
    print("│ All tests fail       │ Verify tool availability       │")
    print("└──────────────────────┴────────────────────────────────┘")
    print()
    print("Next Steps:")
    print("  → Create your home automation agent")
    print("  → Run evaluations and practice debugging")
    print("  → Achieve 100% pass rate!")
    print()


if __name__ == "__main__":
    asyncio.run(demo_analysis_and_fixes())
